apiVersion: v1
kind: Service
metadata:
  name: qultivator-ws
spec:
  ports:
  - name: api
    port: 8080
  selector:
    app: qultivator-ws
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: qultivator-ws
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qultivator-ws
    spec:
      containers:
        - name: server
          image: pmdcosta/qultivator-ws:latest
          resources:
            requests:
              memory: "50Mi"
          ports:
            - containerPort: 8080